name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Get current tag
        id: get-tag
        uses: devops-actions/action-get-tag@v1.0.3
        with:
          strip_v: true

      - name: Update package version to ${{ steps.get-tag.outputs.tag }}
        uses: BellCubeDev/update-package-version-by-release-tag@v2
        with:
          version: ${{ steps.get-tag.outputs.tag }}

      - name: Commit updated package
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: NPM package version updated to ${{ steps.get-tag.outputs.tag }}
          branch: main
          commit_user_name: ${{ github.actor }}
          commit_user_email: ${{ github.actor }}@users.noreply.github.com

      - name: Create Github pre-release
        if: (startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-')) || !startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          draft: true

      - name: Create Github release
        if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-')
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          draft: true
